school:
  topicName: testtopic01

spring:
  kafka:
    properties:
      bootstrap.servers: ${KAFKA_BROKERCONNECT:localhost:8314}
      schema.registry.url: ${SCHEMA_REGISTRY_LISTENERS:http://localhost:8316}

    listener:
      ack-mode: RECORD

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: my-microservice
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true